### ISSUE TITLE
damage tint 1.18.2 

### ISSUE THREAD

**Issue by itzRealDuck** [Polyfrost/DamageTint#1]
are you guys going to make one for 1.18.2? or later versions

**Comment by nxtdaydelivery** [comment]
yes we are soon :tm:

**Comment by MoonTidez** [comment]
nextday is lying it aint soon™️ but it is very much part of the plan
we first want to solidify 1.8.9 tho
and we aren't even **close** to that (reason: mostly me starting uni)

**Comment by huygg123** [comment]
damagetint mod 1.8.9 needs more features like showing /tint armor

**Comment by Wyvest** [comment]
Will be added in OneConfig V1, closing as this is a major feature request that is being addressed in other repos
